# Dockerfile
# Nginx
# Based on CentOS 6

# @date 2017/4/10
# @version 0.1
# @author: ioioj5 <peng_du2007@qq.com>
# Command format: Instruction [arguments / command] ..

# Base image
FROM centos:6

# Maintainer
MAINTAINER ioioj5 peng_du2007@qq.com

# - Commands Start - #

# 1. set up EPEL repository
RUN rpm -Uvh http://mirrors.kernel.org/fedora-epel/6/i386/epel-release-6-8.noarch.rpm
RUN yum repolist

# 2. update the image and install dependencies
RUN yum -y install wget && wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo
RUN yum makecache
RUN yum -y install gcc gcc-c++ gcc-g77 make libtool autoconf patch unzip automake libxml2 libxml2-devel ncurses ncurses-devel libtool-ltdl-devel libtool-ltdl libmcrypt libmcrypt-devel libpng libpng-devel libjpeg-devel openssl openssl-devel curl curl-devel libxml2 libxml2-devel ncurses ncurses-devel libtool-ltdl-devel libtool-ltdl autoconf automake libaio*i

# 3. install Nginx
RUN cd /tmp && wget http://nginx.org/download/nginx-1.11.13.tar.gz && \
	tar -xzvf nginx-1.11.13.tar.gz && \
	cd /tmp/nginx-1.11.13.tar.gz && \
	./configure \
	--prefix=/usr/local/nginx \
	--with-http_ssl_module --with-http_sub_module --with-http_dav_module --with-http_flv_module \
	--with-http_gzip_static_module --with-http_stub_status_module --with-debug && \
	make && \
	make install

# 4. setting nginx conf

# 5. start nginx
ENTRYPOINT ["/etc/init.d/nginx", "start"]

# mount
VOLUME ["/data/www"]

# - Commands End - #
