# Dockerfile
# Php
# Based on CentOS 6

# @date 2017/4/10
# @version 0.1
# @author: ioioj5 <peng_du2007@qq.com>
# Command format: Instruction [arguments / command] ..

# Base image
FROM centos:6

# Maintainer
MAINTAINER ioioj5 peng_du2007@qq.com

# - Commands Start - #
RUN yum -y update && \
    yum install -y gcc automake autoconf libtool make gcc-c++ vixie-cron  wget zlib  file openssl-devel sharutils zip  bash vim cyrus-sasl-devel libmemcached libmemcached-devel libyaml libyaml-devel unzip libvpx-devel openssl-devel ImageMagick-devel  autoconf  tar gcc libxml2-devel gd-devel libmcrypt-devel libmcrypt mcrypt mhash libmcrypt libmcrypt-devel libxml2 libxml2-devel bzip2 bzip2-devel curl curl-devel libjpeg libjpeg-devel libpng libpng-devel freetype-devel bison libtool-ltdl-devel net-tools && \
yum clean all

RUN wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN rpm -ivh epel-release-6-8.noarch.rpm && yum install -y libmcrypt-devel 

RUN cd /tmp && \
	wget http://cn2.php.net/get/php-5.6.30.tar.gz/from/this/mirror -O "php-5.6.30.tar.gz" && \
	tar -xzvf php-5.6.30.tar.gz && \
	cd /tmp/php-5.6.30 && \
	./configure \
	--with-mysqli --with-pdo-mysql --with-iconv-dir --with-freetype-dir --with-jpeg-dir --with-png-dir --with-zlib --with-libxml-dir --enable-simplexml --enable-xml --disable-rpath --enable-bcmath --enable-soap --enable-zip --with-curl --enable-fpm --with-fpm-user=nobody --with-fpm-group=nobody --enable-mbstring --enable-sockets --with-mcrypt --with-gd --enable-gd-native-ttf --with-openssl --with-mhash --enable-opcache && \
	make && \
	make install

# - Commands End - #
